In [1]:
import flask as fk
import types
import pandas as pd
import numpy as np
import sklearn as sk
import scipy as sp
import matplotlib as mp
import seaborn as sea
import xgboost as xg
import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/AddalaTejaswini/DataSet/master/smartbees-loan.csv?token=AJS5HNV2DETXHHISLLW42GS5UDLRI"

In [3]:
dataset = pd.read_csv(url)


In [4]:
dataset.head(9)

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0   25           1      49       4    1.6          1         0   
1   45          19      34       3    1.5          1         0   
2   39          15      11       1    1.0          1         0   
3   35           9     100       1    2.7          2         0   
4   35           8      45       4    1.0          2         0   
5   37          13      29       4    0.4          2       155   
6   53          27      72       2    1.5          2         0   
7   50          24      22       1    0.3          3         0   
8   35          10      81       3    0.6          2       104   

   SecuritiesAccount  CDAccount  CreditCard  PersonalLoan  
0                  1          0           0             0  
1                  1          0           0             0  
2                  0          0           0             0  
3                  0          0           0             0  
4                  0          0           1             0  
5                  0          0           0             0  
6                  0          0           0             0  
7                  0          0           1             0  
8                  0          0           0             0

In [5]:
dataset.isnull().sum()

Age                  0
Experience           0
Income               0
Family               0
CCAvg                0
Education            0
Mortgage             0
SecuritiesAccount    0
CDAccount            0
CreditCard           0
PersonalLoan         0
dtype: int64

In [6]:
y=dataset['PersonalLoan']
print(y.shape)

(5000,)


In [7]:
array = dataset.values
x = array[:,:-1]
y = array[:,10]
x[1]

array([45. , 19. , 34. ,  3. ,  1.5,  1. ,  0. ,  1. ,  0. ,  0. ])

In [8]:
from sklearn.preprocessing import MinMaxScaler 
x1=array[:,:-4]
scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(x1) 
np.set_printoptions(precision=3) 
print(rescaledX[0:2,:]) 

[[0.045 0.087 0.19  1.    0.16  0.    0.   ]
 [0.5   0.478 0.12  0.667 0.15  0.    0.   ]]


In [9]:
x3=x[:,7:]
x3

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [10]:
dummy=pd.get_dummies(dataset['Education'])

In [11]:
x5=pd.DataFrame(rescaledX,columns=['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education', 'Mortgage'])
x5.head()

Age  Experience    Income    Family  CCAvg  Education  Mortgage
0  0.045455    0.086957  0.189815  1.000000   0.16        0.0       0.0
1  0.500000    0.478261  0.120370  0.666667   0.15        0.0       0.0
2  0.363636    0.391304  0.013889  0.000000   0.10        0.0       0.0
3  0.272727    0.260870  0.425926  0.000000   0.27        0.5       0.0
4  0.272727    0.239130  0.171296  1.000000   0.10        0.5       0.0

In [12]:
x6=pd.DataFrame(x3,columns=['Securities Account', 'CD Account', 'CreditCard'])
x6.head()

Securities Account  CD Account  CreditCard
0                 1.0         0.0         0.0
1                 1.0         0.0         0.0
2                 0.0         0.0         0.0
3                 0.0         0.0         0.0
4                 0.0         0.0         1.0

In [13]:
x4 = pd.merge(x5,x6,right_index=True, left_index=True)
x4=x4.drop(['Education'],axis=1)
x4.head()

Age  Experience    Income    Family  CCAvg  Mortgage  \
0  0.045455    0.086957  0.189815  1.000000   0.16       0.0   
1  0.500000    0.478261  0.120370  0.666667   0.15       0.0   
2  0.363636    0.391304  0.013889  0.000000   0.10       0.0   
3  0.272727    0.260870  0.425926  0.000000   0.27       0.0   
4  0.272727    0.239130  0.171296  1.000000   0.10       0.0   

   Securities Account  CD Account  CreditCard  
0                 1.0         0.0         0.0  
1                 1.0         0.0         0.0  
2                 0.0         0.0         0.0  
3                 0.0         0.0         0.0  
4                 0.0         0.0         1.0

In [14]:
x7=pd.merge(x4,dummy,right_index=True, left_index=True)
x7.head()

Age  Experience    Income    Family  CCAvg  Mortgage  \
0  0.045455    0.086957  0.189815  1.000000   0.16       0.0   
1  0.500000    0.478261  0.120370  0.666667   0.15       0.0   
2  0.363636    0.391304  0.013889  0.000000   0.10       0.0   
3  0.272727    0.260870  0.425926  0.000000   0.27       0.0   
4  0.272727    0.239130  0.171296  1.000000   0.10       0.0   

   Securities Account  CD Account  CreditCard  1  2  3  
0                 1.0         0.0         0.0  1  0  0  
1                 1.0         0.0         0.0  1  0  0  
2                 0.0         0.0         0.0  1  0  0  
3                 0.0         0.0         0.0  0  1  0  
4                 0.0         0.0         1.0  0  1  0

In [15]:
dummy.columns=['12th','Bachelors','Masters']
dummy.head()

12th  Bachelors  Masters
0     1          0        0
1     1          0        0
2     1          0        0
3     0          1        0
4     0          1        0

In [16]:
x7=pd.merge(x4,dummy,right_index=True, left_index=True)
x7.head()

Age  Experience    Income    Family  CCAvg  Mortgage  \
0  0.045455    0.086957  0.189815  1.000000   0.16       0.0   
1  0.500000    0.478261  0.120370  0.666667   0.15       0.0   
2  0.363636    0.391304  0.013889  0.000000   0.10       0.0   
3  0.272727    0.260870  0.425926  0.000000   0.27       0.0   
4  0.272727    0.239130  0.171296  1.000000   0.10       0.0   

   Securities Account  CD Account  CreditCard  12th  Bachelors  Masters  
0                 1.0         0.0         0.0     1          0        0  
1                 1.0         0.0         0.0     1          0        0  
2                 0.0         0.0         0.0     1          0        0  
3                 0.0         0.0         0.0     0          1        0  
4                 0.0         0.0         1.0     0          1        0

In [17]:
x7.head()

Age  Experience    Income    Family  CCAvg  Mortgage  \
0  0.045455    0.086957  0.189815  1.000000   0.16       0.0   
1  0.500000    0.478261  0.120370  0.666667   0.15       0.0   
2  0.363636    0.391304  0.013889  0.000000   0.10       0.0   
3  0.272727    0.260870  0.425926  0.000000   0.27       0.0   
4  0.272727    0.239130  0.171296  1.000000   0.10       0.0   

   Securities Account  CD Account  CreditCard  12th  Bachelors  Masters  
0                 1.0         0.0         0.0     1          0        0  
1                 1.0         0.0         0.0     1          0        0  
2                 0.0         0.0         0.0     1          0        0  
3                 0.0         0.0         0.0     0          1        0  
4                 0.0         0.0         1.0     0          1        0

In [18]:
arrayRes = x7.values
arrayRes

array([[0.045, 0.087, 0.19 , ..., 1.   , 0.   , 0.   ],
       [0.5  , 0.478, 0.12 , ..., 1.   , 0.   , 0.   ],
       [0.364, 0.391, 0.014, ..., 1.   , 0.   , 0.   ],
       ...,
       [0.909, 0.913, 0.074, ..., 0.   , 0.   , 1.   ],
       [0.955, 0.935, 0.19 , ..., 0.   , 1.   , 0.   ],
       [0.114, 0.152, 0.347, ..., 1.   , 0.   , 0.   ]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(arrayRes,y,test_size=0.8, random_state=0)

In [21]:
x_train

array([[0.455, 0.478, 0.472, ..., 1.   , 0.   , 0.   ],
       [0.364, 0.37 , 0.144, ..., 0.   , 0.   , 1.   ],
       [0.5  , 0.478, 0.384, ..., 0.   , 1.   , 0.   ],
       ...,
       [0.068, 0.087, 0.074, ..., 0.   , 0.   , 1.   ],
       [0.773, 0.783, 0.19 , ..., 1.   , 0.   , 0.   ],
       [0.227, 0.261, 0.139, ..., 0.   , 0.   , 1.   ]])

In [22]:
x_test

array([[0.705, 0.717, 0.069, ..., 1.   , 0.   , 0.   ],
       [0.227, 0.261, 0.347, ..., 1.   , 0.   , 0.   ],
       [0.705, 0.587, 0.296, ..., 0.   , 0.   , 1.   ],
       ...,
       [0.909, 0.913, 0.704, ..., 1.   , 0.   , 0.   ],
       [0.409, 0.435, 0.208, ..., 1.   , 0.   , 0.   ],
       [0.955, 0.935, 0.046, ..., 0.   , 1.   , 0.   ]])

In [23]:
#y_train

In [24]:
y_test

array([0., 0., 0., ..., 0., 0., 0.])

In [25]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')
model.fit(x_train,y_train)
predictions = model.predict(x_test)
predictions

array([0., 0., 0., ..., 0., 0., 0.])

In [26]:
#u_pred=model.predict(np.array([[0.909, 0.913, 0.352, 0.0, 0.18, 0.0, 1.0, 1.0, 1.0,0.0,0.0,1.0]]))
#u_pred

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
print(accuracy_score(y_test, predictions))

0.9485


In [29]:
from sklearn.tree import DecisionTreeClassifier  
clf = DecisionTreeClassifier(random_state = 0)  
clf.fit(x_train, y_train) 
y_pred = clf.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.98


In [30]:
from sklearn.ensemble import RandomForestClassifier
clf1=RandomForestClassifier(n_estimators=100)
clf1.fit(x_train,y_train)
y_pred=clf1.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.981


In [31]:
import pickle

In [32]:
with open('loan__model__xgboost.pkl', 'wb') as file:
    pickle.dump(model, file)